sudo: false
language: java

jdk:
- oraclejdk7

env:
  global:
	- TERM=dumb
	- secure: "rEVGgSoVV1Nr/kzqmM8Sap5uPBSSk7lwH3K8lZV1T8a3jKsjSlCep0ky+sfBxjziO/n5C3UN7dOIZT4RVYj17QEjS2pqEFHtWxmM5HM0aq5giE/YrjY9lUSyNtNzF2/rRePTS1M/3NkVHisDZ8Hvvd2JW5VDX2uI2LnUjf/4PtR3cR8rJfoXAgJk+5X4qzGcN2u0/bQ56DBg/tIUlnfKjpBi9gATWg7TjeV1aVah+uRXvkLVUV7aPrWpJXRX2XqJbEukp4v/ukO5duyJEKlzUgcF2+Wl5CjusCs9wuwx4KoqQH08VxV5m8iFJi3/pabnykP6YGujks1qy0K63Co6mpzA2+NkCjQd1cmzC1aQ8wC8Qy1DSomfn77+5EXInZ3EDYcq31uaiBDm5GwPxe0F34JsYA7N1tZbE7faohRsfHcJqOfocJCKAFT71w4OaIMA2NOVsnG9/JBnJ7EtKFz9xvOO0WRMYRDU00gQ0/7n0yLd10EiCWwClLiQrQIBe3FsJYmiPqhWO5IXYC/50oBIapmGeRAfR4bRywyJ0y/vRrPlR4sy9Vfh5w9OgSSp5EOz5S4+CO+laOBVxh5/5B+JnEeXa/rHW1+HSd63PMqrsq1NUJjfwgLwS+5QocoP7B2dYc3XWQArwx3bobzDnBUNhtZjPES1rsCsO0jbg4bnNCE="

after_success:
- gradle jacocoTestReport coveralls
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$TAGPERM@github.com/smartcanvas/java-sdk --tags
- ls -R

branches:
  except:
    - /^*-v[0-9]/
    
notifications:
  email: false
  slack:
    rooms:
      - secure: "BZTmqTYVwafXPOwS5D19hISCYj6vBioc5l4C7G6Ce+qibTgPuLC2YX9TV4mupYkYFCV6bZWXw9r3UN0cSrbL2pf5ZXHWQ90lmzvfmcFGNeiahcWXEQf4A8wtVqQ9Aom6cSMZLGX0/chhGfKhvfFprsEMX0n35cTIVIptiKNSZF5iQ9g9QKBtXuV7/wMeamOFp4xa0cBqfq35c/6uS/kDtJVsK0f1+0AmuMENdw4aRFTJi8Fb8Bpfa878HR8iiGYv/k3uSlrLVzsc8eZC0ucgbyuuH2zDUGFZ5snJxPT2AIi9Bz9NQMIqy6/0rnn3uKHZPxNz9ce4wOVQ1f9syQRPEo89D3Em4r+lv6POyixabt70txYRFIAHeQmpQcLwweWV1CtN2OboPEmWdQVojlMwlaUieb1wqPDTPtGM/K3t36uNoEzzRCMqwi2FDuRcij7ZdEoXxjULkKj2NEV92XDT5RIW8iNcPjf47zu0ESNVej6tb0pItR6nmOmI0SgYLuBnssrQlZiYoJpBszaLb4dBa7qG87PnISQgjRqD4cyno6o2VTI2E9jaaMpFE78izf+NLvvv4a9mIoKNlWQc1AJ1li2EubdEGNR4JAIAmMEeUFP1CzKO+NNhTjursoNOm7aqDRwNV7j6BrNRKu9MHZmhBDxQFd+VDvb8TzQvhpPsaZk="