sudo: false
language: java

jdk:
- oraclejdk7

env:
- TERM=dumb

after_success:
- gradle jacocoTestReport coveralls

notifications:
  email: false
  slack:
    rooms:
      - smartcanvas:B1SzslEHZsR4RlapGouUWJYY#development