sudo: false
language: java

jdk:
- oraclejdk7

env:
- TERM=dumb

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/RlonRyan/JBasicX --tags
  - ls -R

after_success:
- gradle jacocoTestReport coveralls

branches:
  except:
    - /^*-v[0-9]/
    
notifications:
  email: false
  slack:
    rooms:
      - smartcanvas:B1SzslEHZsR4RlapGouUWJYY#development